run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - bodyclose
    - nilerr
    - errorlint

linters-settings:
  goimports:
    local-prefixes: github.com/jamesvolpe/basic-budget
  misspell:
    locale: US
  errorlint:
    errorf: true
    asserts: true
    comparison: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
